---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    data_bags_path: ./test/data_bags
    run_list:
      - recipe[apt]
      - recipe[scpr-elasticsearch::default]
      - recipe[scpr-logstash::default]
      - recipe[scpr-logstash::kibana]
    attributes:

