---
driver:
  name: vagrant
  customize:
    memory: 2048

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04

suites:
  - name: default
    run_list:
      - recipe[scpr-logstash::default]
    attributes:
  - name: cluster
    run_list:
      - recipe[scpr-logstash::default]
    attributes:
      scpr_elasticsearch:
        discovery: true
        cluster_name: logstash_test
      scpr_logstash:
        elasticsearch_cluster: logstash_test
